name: dither
version: "0.1.0"
about: "Command Line Interface for the Dither Chat Client"
args:
    - config:
        short: c
        long: config
        value_name: CONFIG
        takes_value: true
        help: Specify the directory to run in
    - debug:
        short: D
        long: debug
        help: Run ipfs command in debug mode
subcommands:
    - peers:
        about: List peers, and info about them
    - friends:
        about: List friends
        takes_value: true
        value_name: CID
        required: true