[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Async
async-std = "1.12.0"
futures = "0.3.25"

# Data
bevy_ecs = "0.9.1"
thiserror = "1.0.38"
eyre = "0.6.8"

# Packet Serialization
rkyv = { version = "0.7.39", features = ["validation"] } # Zero-Copy Serialization
bytecheck = "0.6.9"
rkyv_codec = "0.3.1"
unsigned-varint = "0.7.1"